[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
languages = { version = "0.1.0", path = "../languages" }
syntaxhighlighter = { version = "0.1.0", path = "../syntaxhighlighter" }
