[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
highlight = { version = "0.1.0", path = "../highlight" }
languages = { version = "0.1.0", path = "../languages" }
tokenizer = { version = "0.1.0", path = "../tokenizer" }
